<a href="https://colab.research.google.com/github/Saketkr06/PRML/blob/LInear-Regression/Linear_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sympy
from sympy import init_printing
import numpy as np
from numpy.linalg import inv

init_printing()
np.set_printoptions(precision=3,suppress=True)

In [4]:
phi_01=sympy.symbols('\phi_{0}(x_1)')
phi_02=sympy.symbols('\phi_{0}(x_2)')

phi_11 = sympy.symbols("\phi_{1}(x_1)")
phi_12 = sympy.symbols("\phi_{1}(x_2)")

phi_21 = sympy.symbols("\phi_{2}(x_1)")
phi_22 = sympy.symbols("\phi_{2}(x_2)")

In [6]:
Phi=sympy.Matrix([
    [phi_01,phi_02],
    [phi_11,phi_12],
    [phi_21,phi_22]
])

In [7]:
# N: number of datapoints
# M: number of basis functions
Phi

⎡\phi_{0}(x_1)  \phi_{0}(x_2)⎤
⎢                            ⎥
⎢\phi_{1}(x_1)  \phi_{1}(x_2)⎥
⎢                            ⎥
⎣\phi_{2}(x_1)  \phi_{2}(x_2)⎦

In [8]:
E1=Phi.T @ Phi
E1

⎡                                2                2                2          
⎢                   \phi_{0}(x_1)  + \phi_{1}(x_1)  + \phi_{2}(x_1)           
⎢                                                                             
⎢                                                                             
⎣\phi_{0}(x_1)⋅\phi_{0}(x_2) + \phi_{1}(x_1)⋅\phi_{1}(x_2) + \phi_{2}(x_1)⋅\ph

                                                                              
            \phi_{0}(x_1)⋅\phi_{0}(x_2) + \phi_{1}(x_1)⋅\phi_{1}(x_2) + \phi_{
                                                                              
                                            2                2                
i_{2}(x_2)                     \phi_{0}(x_2)  + \phi_{1}(x_2)  + \phi_{2}(x_2)

                     ⎤
2}(x_1)⋅\phi_{2}(x_2)⎥
                     ⎥
2                    ⎥
                     ⎦

In [10]:
phi_0=sympy.Matrix([[phi_01,phi_02]]).T
phi_1=sympy.Matrix([[phi_11,phi_12]]).T
phi_2=sympy.Matrix([[phi_21,phi_22]]).T

In [11]:
E2=phi_0@phi_0.T + phi_1@phi_1.T + phi_2@phi_2.T
E2

⎡                                2                2                2          
⎢                   \phi_{0}(x_1)  + \phi_{1}(x_1)  + \phi_{2}(x_1)           
⎢                                                                             
⎢                                                                             
⎣\phi_{0}(x_1)⋅\phi_{0}(x_2) + \phi_{1}(x_1)⋅\phi_{1}(x_2) + \phi_{2}(x_1)⋅\ph

                                                                              
            \phi_{0}(x_1)⋅\phi_{0}(x_2) + \phi_{1}(x_1)⋅\phi_{1}(x_2) + \phi_{
                                                                              
                                            2                2                
i_{2}(x_2)                     \phi_{0}(x_2)  + \phi_{1}(x_2)  + \phi_{2}(x_2)

                     ⎤
2}(x_1)⋅\phi_{2}(x_2)⎥
                     ⎥
2                    ⎥
                     ⎦

In [12]:
E1==E2

True

## Geometrical Representation for Least Squares

In [13]:
def pseudoinverse(phi):
  return inv(phi.T@phi)@phi.T

In [14]:
N,M=7,5
Phi=np.random.randn(N,M)
Phi@pseudoinverse(Phi)

array([[ 0.505, -0.268, -0.12 , -0.227, -0.097,  0.264, -0.183],
       [-0.268,  0.852, -0.067, -0.141, -0.027,  0.111, -0.13 ],
       [-0.12 , -0.067,  0.969, -0.069, -0.004,  0.04 , -0.067],
       [-0.227, -0.141, -0.069,  0.78 ,  0.116, -0.079, -0.276],
       [-0.097, -0.027, -0.004,  0.116,  0.761,  0.326,  0.228],
       [ 0.264,  0.111,  0.04 , -0.079,  0.326,  0.517, -0.232],
       [-0.183, -0.13 , -0.067, -0.276,  0.228, -0.232,  0.616]])

In [15]:
v=np.array([2,1,4,1,5,7,1]).reshape(-1,1)
v

array([[2],
       [1],
       [4],
       [1],
       [5],
       [7],
       [1]])

In [16]:
Phi@pseudoinverse(Phi)@v

array([[ 1.215],
       [ 0.419],
       [ 3.693],
       [-0.34 ],
       [ 6.195],
       [ 5.735],
       [-0.907]])

Multiple Outputs

In [17]:
w11,w12,w21,w22=sympy.symbols('w_{11},w_{12},w_{21},w_{22}')
x1,x2=sympy.symbols('x_1,x_2')

W=sympy.Matrix([
    [w11,w12],
    [w21,w22]
])
x=sympy.Matrix([[x1,x2]]).T

In [18]:
((W.T@x).T @ (W.T @ x))[0]

                       2                          2
(w_{11}⋅x₁ + w_{21}⋅x₂)  + (w_{12}⋅x₁ + w_{22}⋅x₂) 

In [19]:
(W.T @ x)@x.T

⎡x₁⋅(w_{11}⋅x₁ + w_{21}⋅x₂)  x₂⋅(w_{11}⋅x₁ + w_{21}⋅x₂)⎤
⎢                                                      ⎥
⎣x₁⋅(w_{12}⋅x₁ + w_{22}⋅x₂)  x₂⋅(w_{12}⋅x₁ + w_{22}⋅x₂)⎦